// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq-BRoG7c2xFGH3L-ZvV5FQ1jPz3JIAZc',
    appId: '1:424831901284:web:df9884845c4711a46c8971',
    messagingSenderId: '424831901284',
    projectId: 'todolist-2024-2',
    authDomain: 'todolist-2024-2.firebaseapp.com',
    storageBucket: 'todolist-2024-2.firebasestorage.app',
    measurementId: 'G-30GZX1L7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpJKXF0wFuOLmi7ZOMIrCMybVUmG7w60',
    appId: '1:424831901284:android:be3903c351d0e6576c8971',
    messagingSenderId: '424831901284',
    projectId: 'todolist-2024-2',
    storageBucket: 'todolist-2024-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXqxYplqlJJ_sqHWCId8xV4Gh2qj0Db8',
    appId: '1:424831901284:ios:4766f72f23b6cf9e6c8971',
    messagingSenderId: '424831901284',
    projectId: 'todolist-2024-2',
    storageBucket: 'todolist-2024-2.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );
}
